# Generated by Django 3.2.9 on 2021-11-09 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='post',
            new_name='post_like',
        ),
    ]
