# Generated by Django 3.2.9 on 2021-11-09 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_rename_post_like_post_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='user',
            new_name='user_like',
        ),
    ]
