# Generated by Django 3.2.9 on 2021-11-13 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0005_rename_user_like_user_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('post', models.ManyToManyField(related_name='tags', to='posts.Post', verbose_name='tags')),
            ],
        ),
    ]
